version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: skt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sktmart
      POSTGRES_PASSWORD: sktmart
      POSTGRES_DB: sktmart
    ports:
      - "5432:5432"
    volumes:
      - skt_pg_data:/var/lib/postgresql/data

volumes:
  skt_pg_data:
